### ISSUE TITLE
Does not comply with CPOL License

### ISSUE THREAD

**Issue by thomas-daniels** [janjongboom/little-maze-game#1]
A part of this code is taken from my [HTML5 Maze Game](http://www.codeproject.com/Articles/577080/Create-an-HTML5-and-JavaScript-Maze-Game-with-a-ti) (this is especially visible in the first commit of your project). The original source files contain a link to my CodeProject profile, but this link has been removed from your project, though this is disallowed by [The Code Project Open License](http://www.codeproject.com/info/cpol10.aspx), which my maze uses:

> You agree not to remove any of the original copyright, patent, trademark, and attribution notices and associated disclaimers that may appear in the Source Code or Executable Files.

You removed the attribution notice from the project. Please re-add it.

**Comment by janjongboom** [comment]
Hi, sure, no problem. I did not recognize the link in HTML as an attribution notice. I would recommend adding it to the JS source as well to avoid confusion.

I added a notice here: https://github.com/janjongboom/mak-maze/blob/master/index.html#L111, let me know if you're OK with this.

**Comment by thomas-daniels** [comment]
Thanks for adding it! I'm certainly fine with your notice. I also included a notice in my JS code, as you suggested.
